
gm_videotheque_categorie:
    resource: "@GMVideothequeBundle/Resources/config/routing/categorie.yml"
    prefix: /categorie

gm_videotheque_film:
    resource: "@GMVideothequeBundle/Resources/config/routing/film.yml"
    prefix: /film