services:
#    gm_videotheque.example:
#        class: GM\VideothequeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     categorie_handler:
         class: GM\VideothequeBundle\Handler\CategorieHandler
         arguments: ["@request_stack", "@doctrine.orm.entity_manager", "@watchdoglogger", "@message_generator", "@form_manager"]

     film_handler:
         class: GM\VideothequeBundle\Handler\FilmHandler
         arguments: ["@request_stack", "@doctrine.orm.entity_manager", "@watchdoglogger", "@message_generator", "@form_manager"]
