<?php

namespace GM\QuestionAnswersBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function onReadBy($readBy = 'id', $attrVal = null){ // put array option which contains ()
        if ($readBy = 'all'){
            $answers = $this->getEntityManager()->getRepository('GMQuestionAnswersBundle:Answer')->findAll();
            return $answers;
        }
        $answers = $this->getEntityManager()->getRepository('GMQuestionAnswersBundle:Answer')->findBy(array($readBy => $attrVal));
        return $answers;
    }
}
