<?php

namespace AppBundle\Repository;

/**
 * WatchDogLoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchDogLoggerRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeAll(){
        $deleteQuery = $this->_em->createQuery('DELETE FROM AppBundle:WatchDogLogger');
        $deleted = $deleteQuery->execute();
        return $deleted;
    }
}
