app:
    resource: '@AppBundle/Controller/'
    type: annotation

gm_phototeque:
    resource: "@GMPhototequeBundle/Resources/config/routing.yml"
    prefix:   /

gm_question_answers:
    resource: "@GMQuestionAnswersBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"