gm_question_answers_answer:
    resource: "@GMQuestionAnswersBundle/Resources/config/routing/answer.yml"
    prefix:   /answer

gm_question_answers_question:
        resource: "@GMQuestionAnswersBundle/Resources/config/routing/question.yml"
        prefix:   /question

gm_question_answers_homepage:
    path:     /
    defaults: { _controller: GMQuestionAnswersBundle:Default:index }
