services:
#    gm_question_answers.example:
#        class: GM\QuestionAnswersBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     answer_handler:
         class: GM\QuestionAnswersBundle\Handler\AnswerHandler
         # arguments: ["@form.factory", "@request_stack", "@doctrine.orm.entity_manager"]
         arguments: [ '@router', "@request_stack", "@form.factory", "@doctrine.orm.entity_manager"]