<?php

namespace GM\PhototequeBundle\Repository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function onReadBy($readBy = 'id', $attrVal = null){ // put array option which contains ()
        if ($readBy == 'all'){
            $photos = $this->getEntityManager()->getRepository('GMPhototequeBundle:Photo')->findAll();
            return $photos;
        }
        $photos = $this->getEntityManager()->getRepository('GMPhototequeBundle:Photo')->findBy(array($readBy => $attrVal));
        return $photos;
    }
}