<?php

namespace GM\VideothequeBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function onReadBy($readBy = 'id', $attrVal = null){ // put array option which contains ()
        if ($readBy == 'all'){
            $answers = $this->getEntityManager()->getRepository('GMVideothequeBundle:Film')->findAll();
            return $answers;
        }
        $answers = $this->getEntityManager()->getRepository('GMVideothequeBundle:Film')->findBy(array($readBy => $attrVal));
        return $answers;
    }
}
