services:
#    gm_phototeque.example:
#        class: GM\PhototequeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


     photo_handler:
         class: GM\PhototequeBundle\Handler\PhotoHandler
         arguments: ["@request_stack", "@doctrine.orm.entity_manager", "@watchdoglogger", "@message_generator", "@form_manager"]
