categorie_index:
    path:     /
    defaults: { _controller: "GMVideothequeBundle:Categorie:index", page: 1, count: 5}
    methods:  [GET, POST]

categorie_pagination:
    path:     /page/{page}
    defaults: { _controller: "GMVideothequeBundle:Categorie:index", page: 1, count: 5}
    methods:  [GET, POST]

categorie_show:
    path:     /{id}/show
    defaults: { _controller: "GMVideothequeBundle:Categorie:show"}
    methods:  [GET, POST]
    requirements:
        id: '\d+'

categorie_new:
    path:     /new
    defaults: { _controller: "GMVideothequeBundle:Categorie:new" }
    methods:  [GET, POST]

categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "GMVideothequeBundle:Categorie:edit" }
    methods:  [GET, POST]
    requirements:
        id: '\d+'

categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "GMVideothequeBundle:Categorie:delete" }
    methods:  DELETE
    requirements:
        id: '\d+'

categorie_delete_all:
    path:     /all/delete
    defaults: { _controller: "GMVideothequeBundle:Categorie:delete_all" }
    methods:  [GET, POST]