categorie_index:
    path:     /
    defaults: { _controller: "GMVideothequeBundle:Categorie:index" }
    methods:  GET

categorie_show:
    path:     /{id}/show
    defaults: { _controller: "GMVideothequeBundle:Categorie:show" }
    methods:  GET
    requirements:
        id: '\d+'

categorie_new:
    path:     /new
    defaults: { _controller: "GMVideothequeBundle:Categorie:new" }
    methods:  [GET, POST]

categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "GMVideothequeBundle:Categorie:edit" }
    methods:  [GET, POST]
    requirements:
        id: '\d+'

categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "GMVideothequeBundle:Categorie:delete" }
    methods:  DELETE
    requirements:
        id: '\d+'
